export const loginStrings = {
  email: "Insira seu email",
  password: "Insira a senha",
  emailError: "Email inválido",
  passwordError: "A senha deve conter no mínimo 7 dígitos",
  labelEmail: "Email",
  emailPlacheholder: "Digite seu email",
  labelPassword: "Senha",
  passwordPlaceholder: "Digite sua senha",
  submit: "Entrar",
  loginNav: "Voltar para o início",
  enterOrSignIn: "Entre ou cadastre-se",
  loginDescription:
    "Para entrar na plataforma é necessário entrar ou criar uma conta.",
  forgotPassword: "Esqueceu a senha?",
  or: "ou",
  signInQuestion: "Ainda não tem uma conta?",
  signIn: "Cadastre-se",
  loading: "Entrando...",
};
